### ISSUE TITLE
Not working with Strange Brigade

### ISSUE THREAD

**Issue by GloriousEggroll** [aejsmith/vkdevicechooser#1]
So, this thing is awesome, I noticed Arlie's PR for mesa and came across this in the comments. However I noticed that while this works for DOOM, for some reason it does not work with Strange Brigade. If you want to skip having to guess where to press on the Strange Brigade launcher for testing, I have a custom proton build that runs the vulkan version of the game directly:

http://github.com/gloriouseggroll/proton-ge-custom

**Comment by aejsmith** [comment]
Unfortunately I don't own Strange Brigade to be able to test this properly. But, since it supports multi-GPU, I'm guessing that it is using `vkEnumeratePhysicalDeviceGroups` rather than `vkEnumeratePhysicalDevices` to enumerate devices, and the layer doesn't currently override that. I'll see if I can implement an override for that over the weekend.

**Comment by aejsmith** [comment]
I've fixed two issues: `vkEnumeratePhysicalDeviceGroups` is now overridden, and the layer .json file now advertises Vulkan 1.1 support (the loader would refuse to load the layer for apps that request 1.1). Hopefully it'll work now!

**Comment by GloriousEggroll** [comment]
yessir that did it! Thanks a ton! 
![Strangebrigade](https://user-images.githubusercontent.com/11287837/64075160-fd9ff480-cc71-11e9-9856-e88cd61150d8.png)
